sudo: required

notifications:
  slack: octograde:rmun1necIqoZSQMQh5QIyWpS

services:
  - docker

before_install:
  - docker build -t dskrenta/solkar .
  - docker run -p 3000:3000 -d dskrenta/solkar

script:
  - exit 0
